name: Database Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: bank
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Initialize Database
      run: |
        mysql -h 127.0.0.1 -P 3306 -u root -proot bank < bank-admin/bank.sql

    - name: Build and Test
      run: mvn -B test --file bank-admin/pom.xml
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/bank?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
        SPRING_REDIS_HOST: localhost
        SPRING_REDIS_PORT: 6379 